### ISSUE TITLE
Does not exclude <head>

### ISSUE THREAD

**Issue by deneuxa** [dblock/actionmailer-text#2]
I'm using http://internations.github.io/antwort/ templates,
so I have an <head> in my html layout like this : 

      <head>
          <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
          <meta name="viewport" content="initial-scale=1.0">    
          <meta name="format-detection" content="telephone=no"> 
      
          <title>MY TITLE</title>
          <style type="text/css">
              .ReadMsgBody { width: 100%; background-color: #ffffff;}
              .ExternalClass {width: 100%; background-color: #ffffff;}
              .ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {line-height:100%;}
              body {-webkit-text-size-adjust:none; -ms-text-size-adjust:none;}
              body {margin:0; padding:0;}
              table {border-spacing:0;}
              table td {border-collapse:collapse;}
              .yshortcuts a {border-bottom: none !important;}
              .circular-avatar{border-radius: 140px;}
              a[class="only_mobile_link"] {
                  display: none;
              }
              /* Constrain email width for small screens */
              @media screen and (max-width: 600px) {
                  table[class="container"] {
                      width: 95% !important;
                  }
                  td[class="removable-col"] {
                      display: none !important;
                  }
                  a[class="only_mobile_link"] {
                      display: inline !important;
                  }
                  td[class="force-col"] {
                      display: block;
                      padding-right: 0 !important;
                  }
              }
      
      
      
          </style>
      </head>

So neither the <title>, neither the CSS code are escaped and appear in my plain-text emails.

The gem could : 
- or escape the <head> part
- or use the default plain text template if existing and include the generated text inside it, what do you think ?

**Comment by woahdae** [comment]
I think #1 fixes this, I'll go release it.

**Comment by deneuxa** [comment]
ah yes,
 didn't see that in the commits,
thanks for the update

2015-05-26 0:41 GMT+02:00 Woody Peterson <notifications@github.com>:

**Comment by woahdae** [comment]
Should be fixed via new release. Let me know if there are still issues.
